language: go

go:
  - "1.14"

services:
  - docker

install:
  - make install
  - make docker
  - ifconfig
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - make release
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $API_KEY
  file_glob: true
  file: dist/*
  on:
    repo: arminc/clair-scanner
    tags: true
